package com.quispe.clinicasalud.ui.theme

import androidx.compose.ui.graphics.Color

// Paleta de colores M3 para Modo Claro
val MdLightPrimary = Color(0xFF00668A)
val MdLightOnPrimary = Color(0xFFFFFFFF)
val MdLightPrimaryContainer = Color(0xFFC3E8FF)
val MdLightOnPrimaryContainer = Color(0xFF001E2C)
val MdLightSecondary = Color(0xFF4E616D)
val MdLightOnSecondary = Color(0xFFFFFFFF)
val MdLightSecondaryContainer = Color(0xFFD1E5F4)
val MdLightOnSecondaryContainer = Color(0xFF0A1E28)
val MdLightTertiary = Color(0xFF006A6A)
val MdLightOnTertiary = Color(0xFFFFFFFF)
val MdLightTertiaryContainer = Color(0xFF9CF1F0)
val MdLightOnTertiaryContainer = Color(0xFF002020)
val MdLightBackground = Color(0xFFF6FAFE)
val MdLightOnBackground = Color(0xFF171C1F)
val MdLightSurface = Color(0xFFF6FAFE)
val MdLightOnSurface = Color(0xFF171C1F)
val MdLightSurfaceVariant = Color(0xFFDCE3E9)
val MdLightOnSurfaceVariant = Color(0xFF40484C)
val MdLightOutline = Color(0xFF70787D)

// Paleta de colores M3 para Modo Oscuro
val MdDarkPrimary = Color(0xFF7BD0FF)
val MdDarkOnPrimary = Color(0xFF00354A)
val MdDarkPrimaryContainer = Color(0xFF004C69)
val MdDarkOnPrimaryContainer = Color(0xFFC3E8FF)
val MdDarkSecondary = Color(0xFFB5C9D7)
val MdDarkOnSecondary = Color(0xFF20333E)
val MdDarkSecondaryContainer = Color(0xFF374955)
val MdDarkOnSecondaryContainer = Color(0xFFD1E5F4)
val MdDarkTertiary = Color(0xFF80D5D4)
val MdDarkOnTertiary = Color(0xFF003737)
val MdDarkTertiaryContainer = Color(0xFF004F4F)
val MdDarkOnTertiaryContainer = Color(0xFF9CF1F0)
val MdDarkBackground = Color(0xFF0F1417)
val MdDarkOnBackground = Color(0xFFDEE3E6)
val MdDarkSurface = Color(0xFF0F1417)
val MdDarkOnSurface = Color(0xFFDEE3E6)
val MdDarkSurfaceVariant = Color(0xFF40484C)
val MdDarkOnSurfaceVariant = Color(0xFFC0C7CD)
val MdDarkOutline = Color(0xFF8A9297)
